# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JF9PRCS9DSYu8onxmqPJeF6RLtd7gdcd
"""

import streamlit as st
import requests
from PIL import Image
import io

API_URL = "https://cifar10-fastapi-deploy-1.onrender.com/predict"

st.set_page_config(page_title="CIFAR-10 Classifier", layout="centered")

st.title("CIFAR-10 Image Classifier")
st.write("Upload an image and get prediction from MobileNetV2")

uploaded_file = st.file_uploader(
    "Choose an image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_container_width=True)

    if st.button("Predict"):
        with st.spinner("Predicting..."):
            files = {
                "file": (
                    uploaded_file.name,
                    uploaded_file.getvalue(),
                    uploaded_file.type
                )
            }

            response = requests.post(API_URL, files=files)

            if response.status_code == 200:
                result = response.json()
                st.success("Prediction completed")

                st.write("**Predicted Class:**", result["predicted_class"])
                st.write("**Confidence:**", f'{result["confidence"]:.2f}')
            else:
                st.error("API Error. Please try again.")

